### ISSUE TITLE
How is this library supposed to be used?

### ISSUE THREAD

**Issue by stoneburner** [TICESoftware/DoubleRatchet#3]
Hi

How is this Library is supposed to be used?

I was able to build this Framework fine by cloning it and doing as suggested by #2 
All the unit tests ran successfully.

Now i would like to use this framework in an ios app.

My first try to just use it as an SPM package failed (hence the issue #2).

I tried to add the build .framework (s) to a new ios project, but i get the same "_Missing required module 'Clibsodium'_" message as before (i added the sodium include files to the search path and added libsodium.a to the framework list.

I even tried to add an ios app target to the DoubleRatched project, and still get the same error (but the framework builds fine and the tests are passing)

So - how do i add this nice framework to an ios app project? 

(and sorry for bothering you again :) )

**Comment by FabioTacke** [comment]
Well, unfortunately the answer won't be satisfying for now. 
In a "raw" Swift project (with SPM) the library can be included  as discussed in #2. In one of our server projects that are written in Swift we do it exactly that way.

However in the case of an iOS project it's more complicated. Theoretically Xcode 11 supports SPM but the feature isn't that powerful yet. I suppose there isn't a way to include quite a complex dependency like this right now. So as an alternative we use CocoaPods to integrate the library in our iOS project. But here comes the unfortunate part: We haven't published the podspecs of DoubleRatchet and it's dependencies in the public CocoaPods repo yet.

I'm going to fix that in the next couple of days and add a usage description for the library in the README.

**Comment by stoneburner** [comment]
Many thanks for that information!

Will happily wait until the podspec is published!

**Comment by cbaykam** [comment]
After breaking my head over this for 2 days, i am glad i am not the only one. Looking forward to the podspec
Thanks

**Comment by FabioTacke** [comment]
Hi there,
I updated the README and published the podspecs for this library and it's dependency. You should now be able to include it into you iOS projects very easily using CocoaPods.

**Comment by stoneburner** [comment]
Very nice from you, thanks!
